[tool.poetry]
name = "Petproject"
version = "1"
description = "Petproject"
authors = ["MelekhSV"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
