name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: #

jobs:
  Backend:
    name: format, lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install poetry
        run: |
            pip install poetry
            poetry install
      - name: lint
        run: |
          make lint
