# Generated by Django 4.0.2 on 2022-02-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("photo", models.ImageField(blank=True, upload_to="")),
                ("description", models.CharField(max_length=300)),
            ],
        )
    ]
