name: CI
on:
  push:
    branches: [master]
  pull_request: #
jobs:
  Frontend:
    name: Lint eslint, prettier
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          working-directory: /frontend/home
          run: |
            npm install
            npm run lint

  Backend:
    name: Lint isort, black, flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install poetry
        run: |
          pip install poetry
          poetry install
      - name: lint
        run: |
          make lint
